app:
  name: docupilot
  port: 8080
  env: development

database:
  driver: postgres
  host: localhost
  port: 5432
  user: user
  password: pass
  dbname: docupilot
  sslmode: disable

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  vhost: "/"
